### ISSUE TITLE
Replace injected web3 use with Provider.

### ISSUE THREAD

**Issue by DiscRiskandBisque** [trufflesuite/drizzle#14]
- Will allow Drizzle to set the `web3` version by instantiating its own.
- Will stop race condition bug where `defaultAccount` is not set in time for a transaction without a `from` field, causing that transaction to fail with confusing error messages; i.e. "incorrect nonce".

**Comment by OliveIT** [comment]
I just faced the same issue and I'm super glad to see @cds-amal has made PR 1 hour ago.
I wish @adrianmcli to approve this PR soon.
BTW Is drizzle v1.5.0 officially released with web3js v1.2.1?

**Comment by cds-amal** [comment]
@OliveIT [web3@"^1.2.1" was merged into develop](https://github.com/trufflesuite/drizzle/pull/11) and will be in the next release (soon).

**Comment by kombos** [comment]
guys, is this issue resolved? looks like it is still injecting Metamask by default, even when a blank drizzleOptions object is defined. There should be an option to prevent drizzle from injecting metamask provider by default. Or otherwise, there should be an option in which, if a customProvider is mentioned (even if a blank object is mentioned as customProvider), then drizzle should stop injecting metamask by default and go to fallback web3 instance.
