### ISSUE TITLE
Drizzle has problem connecting to Infura because of Web3 v1.0.0-beta35

### ISSUE THREAD

**Issue by Muhammad-Altabba** [trufflesuite/drizzle#42]
There is[ a issue ](https://github.com/ethereum/web3.js/issues/1559) with Web3 v1.0.0-beta35 that Drizzle depend on.

Error:
> WebSocket connection to 'wss://mainnet.infura.io/ws'
> failed: Error during WebSocket 
> handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

Web3 has to be [downgraded to v1.0.0-beta33](https://github.com/ethereum/web3.js/issues/1559#issuecomment-412348171) or upgreaded to version v1.0.0-beta36 and above.

**Comment by JasoonS** [comment]
This is working for me right now with the latest version of drizzle (the one at `@drizzle/store`).

There were some strange things happening in my code when I didn't explicitly specify the fixed version of `1.2.1` of web3 in my package.json though (drizzle specifies `^1.2.1`). I don't think this is due to drizzle though, and rather I think there is some kind of interference with the versioning from some of the other dependencies I have (I am integrating walletconnect, portis, torus, fortmatic and squarelink). If this is a concern for you I'll dig up more details, let me know.

So from my side I think this issue can be closed, and I no longer have to maintain a fork with a different web3 version :) (before I in my fork I was using web3 `1.2.0`)

**Comment by jamesmorgan** [comment]
I have this issue in `vue-drizzle` - `failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received` 

* `Vue-drizzle` - `0.1.0`

**Comment by tung-eh** [comment]
@JasoonS  This change haven't released yet, you can look at the code on `master` branch to see the published code.

I also wonder when you guys will release it.

**Comment by adrianmcli** [comment]
@tung-eh Good catch.

@cds-amal We need to make a release this week just based off of what we have right now.

**Comment by cds-amal** [comment]
@tung-eh can you verify if the release solved your issue?

**Comment by friedhelmensch** [comment]
I had the same issue:

> WebSocket connection to 'wss://mainnet.infura.io/ws'
> failed: Error during WebSocket
> handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

 and can confirm that it is solved with the latest release.

as a remark:
https://github.com/trufflesuite/drizzle/issues/42#issuecomment-489356887 

> Error in block processing:
> TypeError: Cannot read property 'transactions' of null

I am seeing the same problem but this is probably a different issue.

**Comment by adrianmcli** [comment]
> can confirm that it is solved with the latest release

Thanks let's close this for now. Regarding the other issue, we'd appreciate opening a new one :)
